import type { PortfolioRecord } from "./types"

// Sample data based on the provided JSON
export const portfolioData: PortfolioRecord[] = [
  {
    id: "ch76z8i00314",
    name: "dalia",
    age: 28,
    height: 163,
    weight: 67,
    haircolour: "black",
    eyecolour: "blue",
    bust: "85d",
    "breast-type": "silicon",
    Konfektion: 36,
    schoesize: 36,
    privatehair: "shaved",
    tattoo: "no",
    smoker: "no",
    nantionality: "TR",
    escort: "yes",
    langDE: "yes",
    langFR: "no",
    langEN: "yes",
    langIT: "no",
    langPL: "no",
    langRO: "no",
    langPT: "no",
    langNL: "no",
    langCN: "no",
    langOTHER: "no",
    descDE:
      "Sie ist die Muse der Mitternacht, von der Sie nicht wussten, dass Sie sie brauchen.\n\nWenn die Stadt schläft, erwacht sie – eine faszinierende 28-jährige Verführerin, die die deutsche Klarheit mit türkischem Temperament vereint. Ein bezaubernder Widerspruch – und das im allerbesten Sinne.\n\nMit Kurven, die Blicke fesseln, und einem Lächeln, das noch lange nachklingt, ist sie mehr als nur schön – sie ist ein Lebensgefühl. Denken Sie an eine Sanduhrfigur, einen betörenden Hüftschwung und einen Po, der definitiv seine eigene Fangemeinde verdient.\n\nAber Schönheit ist nur der Anfang.\n\nWarmherzig, schlagfertig und voller schelmischer Energie bringt sie Licht in jeden Raum – oder verführt Sie in leisen Momenten. Sie spricht fließend Deutsch und noch fließender die Sprache der Verführung – wie eine moderne Scheherazade mit einem Hang zu Spitzenwäsche.\n\nOb bei tiefgründigen Gesprächen oder elektrisierenden Augenblicken: Sie kennt das Spiel der Verführung – und sie spielt es meisterhaft.\n\nIhre Präsenz ist Poesie. Ihr Lachen – berauschend. Ihre Energie? Unaufhaltsam lebendig.\n\nJeden Tag tanzt sie mit Leichtigkeit zwischen den Kulturen – verwurzelt in ihren türkischen Ursprüngen, verbunden mit einem kosmopolitischen Lebensgefühl. Das Ergebnis? Eine Frau wie keine andere, die nicht einfach in Ihr Leben tritt – sie schreitet hinein und schreibt unvergessliche Kapitel.\n\nFür alle, die mehr wollen als nur Schönheit. Für alle, die Charme mit Tiefe suchen, Witz mit Wärme und Leidenschaft mit jeder Berührung spüren wollen – sie ist nicht nur eine Begleiterin. Sie ist ein Erlebnis.",
    descEN:
      "When the city sleeps, she awakens — a captivating 28-year-old enchantress who blends the precision of German poise with the untamed fire of Turkish passion. A dazzling contradiction in the best way possible.\n\nWith curves that turn heads and a smile that lingers long after the night ends, she's more than a vision — she's a vibe. Think hourglass elegance, a hypnotic sway, and a behind that deserves its own fan club.\n\nBut beauty is just the beginning.\n\nWarm-hearted, razor-sharp, and brimming with mischief, she's the kind of woman who can light up a room or steal away into intimate corners with equal ease. Fluent in German and fluent in seduction, she blends old-world charm with a modern spark — like Scheherazade, if she had Instagram and impeccable taste in lingerie.\n\nWhether it's whispered conversations over candlelight or magnetic moments that speak louder than words, she knows how to read the room — and your desires.\n\nHer presence is poetry. Her laughter, intoxicating. Her energy? Unapologetically alive.\n\nEvery day, she dances between cultures with effortless grace — honoring her Turkish roots while embracing a fearless, cosmopolitan spirit. The result? A one-of-a-kind woman who doesn't just walk into your life… she sashays in and turns every encounter into an unforgettable chapter.\n\nFor those who crave more than just beauty. For those who want charm with depth, wit with warmth, and passion that pulses through every touch — she's not just a companion. She's an experience.",
    descFR:
      "Elle est la muse de minuit dont vous ne saviez pas que vous aviez besoin.\n\nQuand la ville s'endort, elle s'éveille — une enchanteresse de 28 ans qui marie la rigueur allemande à la passion brûlante de l'Orient. Un paradoxe fascinant… et absolument irrésistible.\n\nAvec des courbes hypnotiques et un sourire qui laisse des traces, elle n'est pas seulement belle — elle est une ambiance à part entière. Imaginez une silhouette de rêve, une démarche ensorcelante, et des fesses qui mériteraient un hommage artistique.\n\nMais la beauté n'est qu'un prélude.\n\nChaleureuse, espiègle et brillamment libre, elle insuffle une énergie magnétique à chaque instant — que ce soit dans une conversation intime ou un simple regard. Parlant couramment l'allemand et la langue universelle de la séduction, elle évoque une Shéhérazade moderne… avec une touche de dentelle.\n\nEntre confidences murmurées et silences électrisants, elle sait exactement comment captiver — sans jamais forcer.\n\nSa présence est un poème. Son rire, une ivresse. Son énergie ? Intensément vivante.\n\nChaque jour, elle danse entre les cultures — fière de ses racines turques et portée par une modernité assumée. Le résultat ? Une femme unique qui ne fait pas que passer… elle entre en scène et transforme chaque rencontre en un chef-d'œuvre sensuel.\n\nPour ceux qui veulent plus que la beauté. Pour ceux qui cherchent du charme avec du fond, de l'esprit avec de la chaleur, et une passion palpable à chaque instant — elle n'est pas simplement une compagne. Elle est une expérience.",
    descIT:
      "È la musa di mezzanotte che non sapevi ti mancasse.\n\nQuando la città dorme, lei si risveglia – un'incantevole 28enne che unisce la precisione tedesca al fuoco passionale della Turchia. Un mix affascinante, in equilibrio perfetto tra ordine e desiderio.\n\nCon curve magnetiche e un sorriso che lascia il segno, non è solo bella – è un'atmosfera. Immagina una silhouette mozzafiato, un'andatura che incanta e un lato B che meriterebbe un applauso a parte.\n\nMa la bellezza è solo l'inizio.\n\nSpontanea, brillante e maliziosamente libera, illumina ogni stanza o crea intimità con un solo sguardo. Parla perfettamente il tedesco… ma la sua vera lingua è la seduzione. Una moderna Sherazade, con un debole per la lingerie raffinata.\n\nSa come condurre ogni conversazione e ogni momento con grazia e brivido – giocando con la sensualità come un'arte.\n\nLa sua presenza è poesia. Il suo sorriso – inebriante. La sua energia? Vivace e contagiosa.\n\nOgni giorno danza tra culture – orgogliosa delle sue radici turche, aperta al mondo con spirito cosmopolita. Il risultato? Una donna irripetibile che non entra solo nella tua vita – la trasforma in una storia da ricordare.\n\nPer chi cerca più della semplice bellezza. Per chi vuole fascino con profondità, intelligenza con calore e una passione che si sente sulla pelle – lei non è solo una compagna. È un'esperienza.",
    serviceincl_kiss: "yes",
    serviceincl_schmusen: "yes",
    serviceincl_tonguekiss: "yes",
    serviceincl_privatemassage: "yes",
    serviceincl_b2bmassage: "yes",
    serviceincl_erotic: "yes",
    serviceincl_massage: "yes",
    serviceincl_lickballs: "yes",
    serviceincl_girlfriendsex: "yes",
    serviceincl_sexinallpositions: "yes",
    serviceincl_69: "yes",
    serviceincl_Reizwäsche: "yes",
    serviceincl_bathplay: "yes",
    serviceincl_showerplay: "yes",
    serviceincl_bjwith: "yes",
    serviceincl_bjwithout: "yes",
    serviceincl_deepthroat: "yes",
    serviceincl_cumonbody: "yes",
    serviceincl_cummultiple: "yes",
    serviceincl_spanish: "yes",
    serviceincl_strapon: "yes",
    serviceincl_masturbation: "yes",
    serviceincl_dildo: "yes",
    serviceincl_games: "yes",
    serviceincl_dirtytalk: "yes",
    serviceincl_roleplay: "yes",
    serviceincl_facesitting: "yes",
    serviceincl_footfetish: "yes",
    serviceincl_striptease: "yes",
    serviceincl_passivtongueanal: "yes",
    serviceextra_bjcuminmouth: 50,
    serviceextra_bjcuminmouthswallow: 100,
    serviceextra_cumonbody: 50,
    serviceextra_natursektactive: 50,
  },
]
